export const CData = [
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
    {
      marketPlace: "US",
      orgName: "10 Strawberry Street",
      orgOwnerEmail: "org-owner@example.com",
      clientName: "US - 10 Strawberry Street",
      amazonPortalAccount: "US - 10 Strawberry Street ",
      fdMonthlyCronJob: "No",
      overbilling: "Yes",
      financialDashboard: "No",
      invoicing: "No",
      reRunVendors: "No",
    },
  ];


  export const udata = [
    {
        Name: "Yoda",
        UserId: "Yoda112@threecolts.com",
        GrpName: "LeaderTech Group",
        IsAdmin: "No",
        IsInternal: "No",
        
      },
    {
        Name: "Karan",
        UserId: "karan@rebelutionus.com",
        GrpName: "Invoice and Revenue Group",
        IsAdmin: "Yes",
        IsInternal: "Yes",
        
      },
    {
        Name: "Alok",
        UserId: "Alok112@dimetyd.com",
        GrpName: "LeaderTech Group",
        IsAdmin: "Yes",
        IsInternal: "Yes",
        
      },
    {
        Name: "Cody",
        UserId: "cody112@rebelutionus.com",
        GrpName: "FinOps",
        IsAdmin: "No",
        IsInternal: "Yes",
        
      },
    {
        Name: "Justin",
        UserId: "beiber212@gmail.com",
        GrpName: "Ops Group",
        IsAdmin: "No",
        IsInternal: "Yes",
        
      },
    {
        Name: "Kuwar",
        UserId: "kuwar110@threecolts.com",
        GrpName: "Accounting Group",
        IsAdmin: "No",
        IsInternal: "Yes",
        
      },
    
];

export const gdata = [
    {
        Name: "Finance Operations",
        GroupType: "External",
      },
    {
        Name: "Test SG.",
        GroupType: "Internal",
      },
    {
        Name: "Internal User Group",
        GroupType: "Internal",
      },
    {
        Name: "External User Group",
        GroupType: "External",
      },
  ];